# A bash-able template that will fill with variables if correct environment variables are loaded
# source context.{dev | prod}
# eval echo "" > output.yaml

# XStream dev worker configuration
# For notes on setup see docs/development/architecture.md#XStream-Architecture-Setup

version: \"3.7\" #XStream can only support up to 3.7. Using docker 18.06.1-ce

# Default images and setup for worker containers
x-default-worker: &default-worker
  image: ${FULL_IMAGE_NAME}
  env_file: worker.env
  environment:
    - TERACHEM_PBS_PORT=11111
  volumes:
    - tcc-prod-scratch:/scratch

# Default images and setup for terachem containers
x-default-terachem: &default-terachem
  image: mtzgroup/terachem:1.9-2021.02-dev-arch-sm_37-sm_52-sm_61-sm_70
  secrets:
    - source: terachem_licence
      target: /terachem/license.key
  volumes:
    - tcc-prod-scratch:/scratch

# Deploy to xs7-0001 node
x-xs7-0001-deploy: &xs7-0001
  placement:
    constraints:
      - "node.hostname==xs7-0001"

# Celery workers on xs7-0001
x-xs7-0001-worker: &xs7-0001-worker
  <<: *default-worker
  deploy:
    <<: *xs7-0001

# TeraChem servers on xs7-0001
x-xs7-0001-terachem: &xs7-0001-terachem
  <<: *default-terachem
  deploy:
    <<: *xs7-0001

# Deploy to xs7-0002 node
x-xs7-0002-deploy: &xs7-0002
  placement:
    constraints:
      - "node.hostname==xs7-0002"

# Celery workers on xs7-0002
x-xs7-0002-worker: &xs7-0002-worker
  <<: *default-worker
  deploy:
    <<: *xs7-0002

# TeraChem servers on xs7-0002
x-xs7-0002-terachem: &xs7-0002-terachem
  <<: *default-terachem
  deploy:
    <<: *xs7-0002

# Deploy to xs7-0003 node
x-xs7-0003-deploy: &xs7-0003
  placement:
    constraints:
      - "node.hostname==xs7-0003"

# Celery workers on xs7-0003
x-xs7-0003-worker: &xs7-0003-worker
  <<: *default-worker
  deploy:
    <<: *xs7-0003

# TeraChem servers on xs7-0003
x-xs7-0003-terachem: &xs7-0003-terachem
  <<: *default-terachem
  deploy:
    <<: *xs7-0003

services:
  # xs7-0001 Pod 1: GPU 1; NOTE: GPU 0 used by dev
  xs7-0001-worker-1: # name specified via {hostname}-worker-{gpu_number}
    <<: *xs7-0001-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0001-terachem-1 # Must match TeraChem service name below
  xs7-0001-terachem-1: # name specified via {hostname}-terachem-gpu_number}
    <<: *xs7-0001-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=1

  # xs7-0001 Pod 2: GPU 2
  xs7-0001-worker-2: # name specified via {hostname}-worker-{gpu_number}
    <<: *xs7-0001-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0001-terachem-2 # Must match TeraChem service name below
  xs7-0001-terachem-2: # name specified via {hostname}-terachem-gpu_number}
    <<: *xs7-0001-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=2

  # xs7-0001 Pod 3: GPU 3
  xs7-0001-worker-3: # name specified via {hostname}-worker-{gpu_number}
    <<: *xs7-0001-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0001-terachem-3 # Must match TeraChem service name below
  xs7-0001-terachem-3: # name specified via {hostname}-terachem-gpu_number}
    <<: *xs7-0001-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=3

  # xs7-0002 Pod 1: GPU 1; NOTE: GPU 0 used by dev
  xs7-0002-worker-1:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-1
  xs7-0002-terachem-1:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=1

  # xs7-0002 Pod 2: GPU 2
  xs7-0002-worker-2:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-2
  xs7-0002-terachem-2:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=2

  # xs7-0002 Pod 3: GPU 3
  xs7-0002-worker-3:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-3
  xs7-0002-terachem-3:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=3

  # xs7-0002 Pod 4: GPU 4
  xs7-0002-worker-4:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-4
  xs7-0002-terachem-4:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=4

  # xs7-0002 Pod 5: GPU 5
  xs7-0002-worker-5:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-5
  xs7-0002-terachem-5:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=5

  # xs7-0002 Pod 6: GPU 6
  xs7-0002-worker-6:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-6
  xs7-0002-terachem-6:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=6

  # xs7-0002 Pod 7: GPU 7
  xs7-0002-worker-7:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-7
  xs7-0002-terachem-7:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=7

  # xs7-0002 Pod 8: GPU 8
  xs7-0002-worker-8:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-8
  xs7-0002-terachem-8:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=8

  # xs7-0002 Pod 9: GPU 9
  xs7-0002-worker-9:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-9
  xs7-0002-terachem-9:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=9

  # xs7-0002 Pod 10: GPU 10
  xs7-0002-worker-10:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-10
  xs7-0002-terachem-10:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=10

  # xs7-0002 Pod 11: GPU 11
  xs7-0002-worker-11:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-11
  xs7-0002-terachem-11:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=11

  # xs7-0002 Pod 12: GPU 12
  xs7-0002-worker-12:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-12
  xs7-0002-terachem-12:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=12

  # xs7-0002 Pod 13: GPU 13
  xs7-0002-worker-13:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-13
  xs7-0002-terachem-13:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=13

  # xs7-0002 Pod 14: GPU 14
  xs7-0002-worker-14:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-14
  xs7-0002-terachem-14:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=14

  # xs7-0002 Pod 15: GPU 15
  xs7-0002-worker-15:
    <<: *xs7-0002-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0002-terachem-15
  xs7-0002-terachem-15:
    <<: *xs7-0002-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=15

  # xs7-0003 Pod 0: GPU 0
  xs7-0003-worker-0:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-0
  xs7-0003-terachem-0:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=0

  # xs7-0003 Pod 1: GPU 1;
  xs7-0003-worker-1:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-1
  xs7-0003-terachem-1:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=1

  # xs7-0003 Pod 2: GPU 2
  xs7-0003-worker-2:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-2
  xs7-0003-terachem-2:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=2

  # xs7-0003 Pod 3: GPU 3
  xs7-0003-worker-3:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-3
  xs7-0003-terachem-3:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=3

  # xs7-0003 Pod 4: GPU 4
  xs7-0003-worker-4:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-4
  xs7-0003-terachem-4:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=4

  # xs7-0003 Pod 5: GPU 5
  xs7-0003-worker-5:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-5
  xs7-0003-terachem-5:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=5

  # xs7-0003 Pod 6: GPU 6
  xs7-0003-worker-6:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-6
  xs7-0003-terachem-6:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=6

  # xs7-0003 Pod 7: GPU 7
  xs7-0003-worker-7:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-7
  xs7-0003-terachem-7:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=7

  # xs7-0003 Pod 8: GPU 8
  xs7-0003-worker-8:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-8
  xs7-0003-terachem-8:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=8

  # xs7-0003 Pod 9: GPU 9
  xs7-0003-worker-9:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-9
  xs7-0003-terachem-9:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=9

  # xs7-0003 Pod 10: GPU 10
  xs7-0003-worker-10:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-10
  xs7-0003-terachem-10:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=10

  # xs7-0003 Pod 11: GPU 11
  xs7-0003-worker-11:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-11
  xs7-0003-terachem-11:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=11

  # xs7-0003 Pod 12: GPU 12
  xs7-0003-worker-12:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-12
  xs7-0003-terachem-12:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=12

  # xs7-0003 Pod 13: GPU 13
  xs7-0003-worker-13:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-13
  xs7-0003-terachem-13:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=13

  # xs7-0003 Pod 14: GPU 14
  xs7-0003-worker-14:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-14
  xs7-0003-terachem-14:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=14

  # xs7-0003 Pod 15: GPU 15
  xs7-0003-worker-15:
    <<: *xs7-0003-worker
    environment:
      - TERACHEM_PBS_HOST=xs7-0003-terachem-15
  xs7-0003-terachem-15:
    <<: *xs7-0003-terachem
    environment:
      - NVIDIA_VISIBLE_DEVICES=15

secrets:
  terachem_licence:
    external: true

volumes:
  tcc-prod-scratch:
