# A bash-able template that will fill with variables if correct environment variables are loaded
# source context.{dev | prod}
# eval "echo \"$(cat $(pwd)/docker-compose.template.yaml)\"" > output.yaml
version: \"3.8\"

services:
  web-server:
    image: ${FULL_IMAGE_NAME}
    networks:
      - traefik-public
    env_file: server.env
    deploy:
      update_config:
        parallelism: 1
        order: start-first
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.qcc-web-server.rule=Host(${WEBSERVER_TRAEFIK_HOST})
        - traefik.http.routers.qcc-web-server.entrypoints=https
        - traefik.http.routers.qcc-web-server.tls=true
        - traefik.http.routers.qcc-web-server.tls.certresolver=le
        - traefik.http.services.qcc-web-server-service.loadbalancer.server.port=8000
networks:
  traefik-public:
    external: true
