version: "3.8"

services:
  web-server:
    build:
      context: ../.
      dockerfile: ./docker/server.dockerfile
    ports:
      - 8000:8000
    environment:
      # Connect to rabbit and redis over docker network instead of locahost
      - CELERY_BROKER_CONNECTION_STRING=amqp://mq
      - CELERY_BACKEND_CONNECTION_STRING=redis://redis/0
    env_file:
      - ../.env
    volumes:
      - ../terachem_cloud:/code/terachem_cloud
    command: uvicorn --host 0.0.0.0 --port 8000 terachem_cloud.main:app --reload

  worker:
    build:
      context: ../.
      dockerfile: ./docker/celeryworker.dockerfile
    depends_on:
      - mq
      - redis
    environment:
      - CELERY_BROKER_CONNECTION_STRING=amqp://mq
      - CELERY_BACKEND_CONNECTION_STRING=redis://redis/0
    env_file:
      - ../.env
    volumes:
      - ../terachem_cloud:/code/terachem_cloud

  mq:
    ports:
      # Open rabbit to locahost for dev container access
      - 5672:5672
      - 15672:15672

  redis:
    ports:
      # Open redis to locahost for dev container access
      - 6379:6379
